# Generated by Django 6.1 on 2026-08-31 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_teacherattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='assigned_class',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
