# Generated by Django 6.1 on 2026-09-01 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_teacher_assigned_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='employment_type',
            field=models.CharField(choices=[('full', 'Full-time'), ('part', 'Part-time')], default='full', max_length=10),
        ),
    ]
